import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* BBH Bogle */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=BBH+Bogle:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />

        {/* Merriweather */}
        <link
          href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className={`${geistMono.variable} antialiased`}>
        <Header />

        {/* ✅ Responsive offset for fixed header */}
        <main className="
          pt-[80px]   /* mobile (logo + categories row) */
          md:pt-[56px] /* desktop */
        ">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
