import { Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-body",
  display: "swap",
});

export const metadata = {
  title: "TIMESCHRONICLE",
  description: "Generated by Timeschronicle",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistMono.variable}
          ${merriweather.variable}
          antialiased
        `}
      >
        <Header />

        <main className="pt-[80px] md:pt-[56px]">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}